## Change server port
server:
  port: 8090

## Connect to database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-sql:5432/jwt_security
    username: postgres
    password: Lbc6z)n5kI

## Configure JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

## Store secret key and define token expiration time
application:
  security:
    jwt:
      secret-key: c606de64c81a4c4e8549bac747ef5d15cef225efcbc79d15d3331f018614ea86
      expiration:
        access-token: 86400000
        refresh-token: 604800000